language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: XO/V4h/oHeT8MtGAXhkMAOHheJBgbn0gFMjASUNoMj2gyUxFRxamubdO5BHFkb/WMTSdjkWIMuXW6x3cZvUZM8p16l9gGkGgaaWFasGKMHX1msLau3fLUzcoUF2a8sUYTHiqa1RFzERWxKJi9ETaw8enfxvDdlmLrRjvueB97epd81Wu18sy//dakOV8uKaVXzz7Btiru0qndSC2v2b1o3g1ghK9mxYc9QVE5B9b4jYCq8wwe9jtwdTPYa3wjZWOKua4WL/l59wxYPy/EsDTaFqY9urK6OKUjuzV/D3CE2MyhQVAH7ZOyYb1B++V1qblIwcRJOF8QInzhHqaKBuC4foCwQ6dCVF7sKINXIPGboNDRetR5it/bOtA4RV212JSyszJLfs6xCpAAOVOLg/kXmIOXGWdrCL19pzXHSUBO+Dv/iLyrsqsiP94GXvpYkKumdyK57hDty7Hi9kKIK/Nmsa5iuROqWyUB9WMdiB9SqOm07rVtmR0DekC9ixr9OzbJRHYbpvBx6Itk+prhng11l/kypaOWSHA8bFezoN5v2dG0IP89fvo6CKZKtsSQ/JcsNgykfTRzMs93OFqARPYdjgdw+qGvRhkugyTS5bGc0/dUmz0c1tyCc26tvowBJqbPzVHRRwY4tcSKyaJ1rqKlV3IhynUH3DjdeahbeEpEkY=
  app: flask-bioinformatics
  on:
    repo: zhangway/flask-bioinformatics
env:
  global:
    secure: KAqmP6TSMLp9fYoQd+XVOBUTNY30JVS30Vd7f0WfLK5XK4LJxSa+95se0kGxe4txRtSUOFKXLhAnaBEb+KPsulXorKee7ajwlmmPgnsU++nJRicBfowqDsabahq0bnklY9KTG2nyjQ49D+BguvZdmgIDboWs8JLDLeIqaDP7EkRTd/7XYIegRu3wdR8gOTFyyDZdFC9Y3/M+T2w4mZVt8SHV7oNb4dbcAr7UOlTfo6O4AYfGr0GC3lS+7KFqYGr4v9+1OzrvXhfJ/T6CaTT5ELp3tGuAlhJ2hyHcUh28O4VWYilh9wcXTRUI2zi3sbfxZeFD/WM8GLkxdnc0I49QF5ujrilcsXmLMVnEARFAxbaYHYQBrV2+5OqUmTzRma7WExLQKQhcnrc4h61boCf/iF5To9xbO3I1doiSE9aprRxd3lF1yf39VJqsmCcqAdlkzj+soycC65nNUQVbRs0kq8E0RnrjEIUEWRhPKZIj+n4wz4DPi3LlbbwVFHx1NEyf70HBHvRXKZ9uNn/00B5eLFHaiQqzF9eZEaYkJ6a90GjwXefBsr/tIKWM+t8QtugbxFt5wObNYzG0A45Sco0a2IVjfn8yrKcOtZhA+eeBLmKZRkxWw7fJmC8Inthp6kpmLFji9hUydBMJMU1/6vzFJ7qNhx4q+umlVYcIwVF6qO8=
