language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: "GawzVgFoQFSA2tMa/6SDvJmIrxI9giqhjeZLG/pl1LVbTw4mKiv88XJaGQXjjiB7e+sUZh04RBeEk+llCHNvYCWgwDCeVPhIVqmVnhcX9lebQ1PWFN3BSJDEg4sMqKzC8Ei6vDGwAH5s4LGmV52Pnbvh0iTLCxPP3OWUoXhHsfnQkwqegSDDjrWe1BmFXL4FrxjWLaEBRQFPms/rCaDdZarHGECClZVgG4y2S4wqHxlQsqoi+vmp+r5XJADBbNPOSgrHb8EU12j89rZZZ/5+uOIozPjDEIG1+clcY1tJCKL990W6bObYEWCdaOBWK10qK7eQ4Gxux8+/VWQZZ4HQ1K9STzJGhlzX1n14OytU5ourAvB/urIDg04kNFqrws5IRPFYVFEdZGqM86UVX8rKkksTaqLuN7uIHvPSSF7P5mXjmWSCwbA6wEbp/egNrw0DdhvhgnWNw58gjg+Z1nLIw5QYWk9c9TkcbdkTSpd1dIxJIGm1RJ44UbYDJ/L93cbK26B5L5eiceBavNA9qbT//ejDZn1cILPZtCKqh+Ac6Nhe4dTHjDilUJ6x58ZsFgvDa1KmQm6ELls90AzQZqQOSo4/1cFFOW0EvZKppCDU/E7KoVDN+wMOhGmJqLOZXwDWniXUyCMrvHrzr6N0qI6vFwFKyvox//YzkEhyl5DiO88="
  app: flask-bioinformatics
  on:
    repo: zhangway/flask-bioinformatics
