language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: "D6Ax+Q8A/mAGDemMi15hntDxZh+bRJ6qNpYuLe0b7BfIzrebcISA9CnsDNFnXjRngfJ301vslKofz7oZNb+iimRYhkPCkHM8/1sRUFBhf+pSpn6dKXNecez/FoBsLVJYLDrXR5vPE5c1dk2DbzgZPfcqR63f7vi1utfScoc8wGdk2WGrb5dopBDO9TxUcPfWoVsuVtv2GVg/EEuEXCG7fg8NYQ4rD5D9RnN7XaHgBQiz4B41ulh5MKbqJfUB+qj49AOkanjiwMmoFZK+lJ7CNmv9zaF18aa8BX2nDmIkbbGR/a9wRgUI+6iNP9Bu9gm4GFxeLwgtD351OMkLWCv9NF5A7LoPx4ayUiVMXH3x1ut6mXhVliOOIzTp8Pi7OWMlb7qvILN80tL5gHAI829FBIzObSo+xN72galqSt++qHcUPINNr+kR0iuuht2OXLdrPaDtOQH+iOxLIUbld+CpwHu8tuB3RXr2AcIPHMFgl2tL4mBSKpgdU24PcdiP3UCJGDB9ftx/1Op1O27czPNH84kdaGXxp6RltBs/RXst5IO+5cuRzxAc1rVjGE00rmZ4Q/Chs7zGGjYXqAzGBBoxH+/MQbjQF832V0UuxTmws9mrjlpQUf9QkhASCB3wtXiscCPRi9BCz/sZK7d/pn+DijzJ0Jbt5FZGUZ61aB7jA3Y="
  app: flask-bioinformatics
  on:
    repo: zhangway/flask-bioinformatics
